version: "2"

services:
  openbazaard:
    build: "."
    network_mode: "host"
    ports:
      - "18467:18467"
      - "18469:18469/udp"
      - "18466:18466"
      - "18470:18470"
    volumes:
      - "./data:/root/.openbazaar"
    environment:
        # Should be changed to more secure values
      - "USERNAME=username"
      - "PASSWORD=password"